package dev.repodoctor.service;

import dev.repodoctor.model.Attempt;
import dev.repodoctor.model.Job;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Generates intelligent PR titles and descriptions based on fix data.
 *
 * The generated content includes:
 * - Concise title summarizing the fix
 * - What was broken (from baseline analysis)
 * - What was fixed (from successful attempt)
 * - Test improvement metrics
 * - AI confidence assessment
 * - Risk level indicator
 */
@Service
public class PullRequestGenerator {

    private static final String REPODOCTOR_BADGE = "🤖 Generated by [RepoDoctor](https://github.com/teja230/repo-doctor)";

    /**
     * Generate a PR title based on the fix.
     *
     * Format: "Fix N failing tests in {repo}" or "Fix {component} in {repo}"
     * Examples:
     * - "Fix 2 failing tests in my-project"
     * - "Fix Calculator logic in my-project"
     * - "Fix test assertions in my-project"
     */
    public String generateTitle(Job job, Attempt successfulAttempt, Attempt baselineAttempt) {
        int baselineFailed = baselineAttempt.getTestsFailed() != null ? baselineAttempt.getTestsFailed() : 0;
        int successFailed = successfulAttempt.getTestsFailed() != null ? successfulAttempt.getTestsFailed() : 0;
        int testsFixed = baselineFailed - successFailed;
        String repoName = job.getRepoName() != null ? job.getRepoName() : "repository";

        // Try to extract a short component name from the patch or explanation
        String component = extractComponentName(successfulAttempt.getExplanation());

        String title;
        if (testsFixed > 0) {
            // Primary: focus on number of tests fixed
            if (component != null) {
                title = String.format("Fix %s (%d test%s) in %s",
                        component, testsFixed, testsFixed != 1 ? "s" : "", repoName);
            } else {
                title = String.format("Fix %d failing test%s in %s",
                        testsFixed, testsFixed != 1 ? "s" : "", repoName);
            }
        } else if (component != null) {
            // Fallback: component-based title
            title = String.format("Fix %s in %s", component, repoName);
        } else {
            // Last resort: generic title
            title = String.format("Fix build issues in %s", repoName);
        }

        return formatTitle(title);
    }

    /**
     * Extract a short component/class name from the explanation.
     * Looks for patterns like "ClassName", "method_name", or key terms.
     */
    private String extractComponentName(String explanation) {
        if (explanation == null || explanation.isBlank()) {
            return null;
        }

        // Look for class names (PascalCase words)
        Pattern classPattern = Pattern.compile("\\b([A-Z][a-z]+(?:[A-Z][a-z]+)+)\\b");
        Matcher classMatcher = classPattern.matcher(explanation);
        if (classMatcher.find()) {
            return classMatcher.group(1);
        }

        // Look for method references like "methodName()" or "method_name"
        Pattern methodPattern = Pattern.compile("\\b([a-z][a-zA-Z]+)\\s*\\(\\)");
        Matcher methodMatcher = methodPattern.matcher(explanation);
        if (methodMatcher.find()) {
            return methodMatcher.group(1) + "()";
        }

        // Look for common keywords
        String lowerExplanation = explanation.toLowerCase();
        if (lowerExplanation.contains("null")) return "null handling";
        if (lowerExplanation.contains("assertion")) return "test assertions";
        if (lowerExplanation.contains("import")) return "imports";
        if (lowerExplanation.contains("dependency")) return "dependencies";
        if (lowerExplanation.contains("configuration")) return "configuration";

        return null;
    }

    /**
     * Format title with consistent style and [RepoDoctor] suffix
     */
    private String formatTitle(String title) {
        // Remove any trailing punctuation
        title = title.replaceAll("[.!?]+$", "");

        // Ensure title case for first letter
        if (!title.isEmpty()) {
            title = Character.toUpperCase(title.charAt(0)) + title.substring(1);
        }

        // Add RepoDoctor suffix
        return title + " [RepoDoctor]";
    }

    /**
     * Generate a comprehensive PR description.
     */
    public String generateDescription(Job job, Attempt successfulAttempt, Attempt baselineAttempt,
                                       List<Attempt> allAttempts, String patchContent) {
        StringBuilder sb = new StringBuilder();

        // Header with summary
        sb.append("## Summary\n\n");
        sb.append(generateSummarySection(job, successfulAttempt, baselineAttempt));
        sb.append("\n\n");

        // What was broken
        sb.append("## Problem\n\n");
        sb.append(generateProblemSection(baselineAttempt));
        sb.append("\n\n");

        // What was fixed
        sb.append("## Solution\n\n");
        sb.append(generateSolutionSection(successfulAttempt));
        sb.append("\n\n");

        // Test improvements
        sb.append("## Test Results\n\n");
        sb.append(generateTestResultsSection(baselineAttempt, successfulAttempt));
        sb.append("\n\n");

        // Risk assessment
        sb.append("## Risk Assessment\n\n");
        sb.append(generateRiskSection(successfulAttempt));
        sb.append("\n\n");

        // Files changed (extracted from patch)
        List<String> filesChanged = extractFilesFromPatch(patchContent);
        if (!filesChanged.isEmpty()) {
            sb.append("## Files Changed\n\n");
            for (String file : filesChanged) {
                sb.append("- `").append(file).append("`\n");
            }
            sb.append("\n");
        }

        // Attempt history (if multiple attempts)
        if (allAttempts.size() > 2) { // More than baseline + 1 attempt
            sb.append("## Fix Attempts\n\n");
            sb.append(generateAttemptHistorySection(allAttempts));
            sb.append("\n");
        }

        // Footer
        sb.append("---\n\n");
        sb.append(REPODOCTOR_BADGE).append("\n\n");
        sb.append("<details>\n");
        sb.append("<summary>ℹ️ About this PR</summary>\n\n");
        sb.append("This pull request was automatically generated by RepoDoctor, an AI-powered build fixing agent.\n\n");
        sb.append("- **Build Tool**: ").append(job.getBuildTool()).append("\n");
        sb.append("- **Attempts**: ").append(allAttempts.size() - 1).append("\n");
        sb.append("- **AI Model**: Gemini 3 Flash\n\n");
        sb.append("Please review the changes carefully before merging.\n");
        sb.append("</details>\n");

        return sb.toString();
    }

    // === Private helper methods ===

    private String generateSummarySection(Job job, Attempt successfulAttempt, Attempt baselineAttempt) {
        int baselineFailed = baselineAttempt.getTestsFailed() != null ? baselineAttempt.getTestsFailed() : 0;
        int successFailed = successfulAttempt.getTestsFailed() != null ? successfulAttempt.getTestsFailed() : 0;
        int fixed = baselineFailed - successFailed;

        StringBuilder summary = new StringBuilder();

        if (fixed > 0) {
            summary.append(String.format("✅ **Fixed %d failing test%s** in `%s`\n\n",
                    fixed, fixed != 1 ? "s" : "", job.getRepoName()));
        } else {
            summary.append(String.format("✅ **Build issues resolved** in `%s`\n\n", job.getRepoName()));
        }

        if (successfulAttempt.getExplanation() != null) {
            // Get first 2 sentences for summary
            String briefExplanation = getFirstSentences(successfulAttempt.getExplanation(), 2);
            summary.append(briefExplanation);
        }

        return summary.toString();
    }

    private String generateProblemSection(Attempt baselineAttempt) {
        StringBuilder sb = new StringBuilder();

        if (baselineAttempt.getExplanation() != null && !baselineAttempt.getExplanation().isBlank()) {
            sb.append(baselineAttempt.getExplanation());
        } else {
            // Construct from test counts
            int testsRun = baselineAttempt.getTestsRun() != null ? baselineAttempt.getTestsRun() : 0;
            int testsFailed = baselineAttempt.getTestsFailed() != null ? baselineAttempt.getTestsFailed() : 0;

            if (testsFailed > 0) {
                sb.append(String.format("The baseline build had **%d of %d tests failing**.", testsFailed, testsRun));
            } else if (baselineAttempt.getExitCode() != null && baselineAttempt.getExitCode() != 0) {
                sb.append(String.format("The build failed with exit code **%d**.", baselineAttempt.getExitCode()));
            } else {
                sb.append("The build was failing.");
            }
        }

        return sb.toString();
    }

    private String generateSolutionSection(Attempt successfulAttempt) {
        StringBuilder sb = new StringBuilder();

        if (successfulAttempt.getExplanation() != null && !successfulAttempt.getExplanation().isBlank()) {
            sb.append(successfulAttempt.getExplanation());
        } else {
            sb.append("Applied automated fix to resolve the failing tests.");
        }

        return sb.toString();
    }

    private String generateTestResultsSection(Attempt baselineAttempt, Attempt successfulAttempt) {
        StringBuilder sb = new StringBuilder();

        int baselineRun = baselineAttempt.getTestsRun() != null ? baselineAttempt.getTestsRun() : 0;
        int baselinePassed = baselineAttempt.getTestsPassed() != null ? baselineAttempt.getTestsPassed() : 0;
        int baselineFailed = baselineAttempt.getTestsFailed() != null ? baselineAttempt.getTestsFailed() : 0;

        int successRun = successfulAttempt.getTestsRun() != null ? successfulAttempt.getTestsRun() : 0;
        int successPassed = successfulAttempt.getTestsPassed() != null ? successfulAttempt.getTestsPassed() : 0;
        int successFailed = successfulAttempt.getTestsFailed() != null ? successfulAttempt.getTestsFailed() : 0;

        sb.append("| Metric | Before | After |\n");
        sb.append("|--------|--------|-------|\n");
        sb.append(String.format("| Tests Run | %d | %d |\n", baselineRun, successRun));
        sb.append(String.format("| Passed | %d | %d |\n", baselinePassed, successPassed));
        sb.append(String.format("| Failed | %d | %d |\n", baselineFailed, successFailed));

        if (baselineFailed > successFailed) {
            sb.append(String.format("\n🎉 **%d test%s now passing!**",
                    baselineFailed - successFailed,
                    (baselineFailed - successFailed) != 1 ? "s" : ""));
        }

        return sb.toString();
    }

    private String generateRiskSection(Attempt successfulAttempt) {
        StringBuilder sb = new StringBuilder();

        String riskLevel = successfulAttempt.getRiskLevel();
        if (riskLevel == null) {
            riskLevel = "UNKNOWN";
        }

        String emoji;
        String description;
        switch (riskLevel.toUpperCase()) {
            case "LOW":
                emoji = "🟢";
                description = "Safe, minimal change - Low risk of side effects";
                break;
            case "MEDIUM":
                emoji = "🟡";
                description = "Moderate complexity - Review recommended";
                break;
            case "HIGH":
                emoji = "🔴";
                description = "Significant changes - Careful review required";
                break;
            default:
                emoji = "⚪";
                description = "Risk level not assessed";
        }

        sb.append(String.format("**Risk Level**: %s %s\n\n", emoji, riskLevel));
        sb.append(description);

        if (successfulAttempt.getConfidenceNotes() != null && !successfulAttempt.getConfidenceNotes().isBlank()) {
            sb.append("\n\n**AI Confidence Notes**:\n> ");
            sb.append(successfulAttempt.getConfidenceNotes().replace("\n", "\n> "));
        }

        return sb.toString();
    }

    private String generateAttemptHistorySection(List<Attempt> allAttempts) {
        StringBuilder sb = new StringBuilder();

        sb.append("| Attempt | Status | Tests Passed | Risk |\n");
        sb.append("|---------|--------|--------------|------|\n");

        for (Attempt attempt : allAttempts) {
            if (attempt.getAttemptNumber() == 0) {
                sb.append(String.format("| Baseline | %s | %d/%d | - |\n",
                        attempt.getStatus(),
                        attempt.getTestsPassed() != null ? attempt.getTestsPassed() : 0,
                        attempt.getTestsRun() != null ? attempt.getTestsRun() : 0));
            } else {
                sb.append(String.format("| %d | %s | %d/%d | %s |\n",
                        attempt.getAttemptNumber(),
                        attempt.getStatus(),
                        attempt.getTestsPassed() != null ? attempt.getTestsPassed() : 0,
                        attempt.getTestsRun() != null ? attempt.getTestsRun() : 0,
                        attempt.getRiskLevel() != null ? attempt.getRiskLevel() : "-"));
            }
        }

        return sb.toString();
    }

    private List<String> extractFilesFromPatch(String patchContent) {
        if (patchContent == null || patchContent.isBlank()) {
            return List.of();
        }

        // Pattern to match "diff --git a/path b/path" or "+++ b/path"
        Pattern pattern = Pattern.compile("^\\+\\+\\+ b/(.+)$", Pattern.MULTILINE);
        Matcher matcher = pattern.matcher(patchContent);

        java.util.Set<String> files = new java.util.LinkedHashSet<>();
        while (matcher.find()) {
            files.add(matcher.group(1));
        }

        return List.copyOf(files);
    }

    private String getFirstSentences(String text, int count) {
        if (text == null || text.isBlank()) {
            return "";
        }

        // Split by sentence-ending punctuation
        String[] sentences = text.split("(?<=[.!?])\\s+");

        StringBuilder result = new StringBuilder();
        for (int i = 0; i < Math.min(count, sentences.length); i++) {
            if (i > 0) {
                result.append(" ");
            }
            result.append(sentences[i].trim());
        }

        return result.toString();
    }
}
